local M = {}
function M.setup()
  vim.api.nvim_set_hl(0, 'Normal', { fg = '#4A2C0A', bg = '#FFF8F0' })
  vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#4A2C0A', bg = '#EDE0CC' })
  vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#EDE0CC' })
  vim.api.nvim_set_hl(0, 'LineNr', { fg = '#B8693A' })
  vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#C8834A', bold = true })
  vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#FFF8F0' })
  vim.api.nvim_set_hl(0, 'FoldColumn', { bg = '#FFF8F0' })
  vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#4A2C0A', bg = '#F5EBD8' })
  vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#4A2C0A', bg = '#EDE0CC', bold = true })
  vim.api.nvim_set_hl(0, 'Search', { fg = '#FFF8F0', bg = '#C8834A' })
  vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#4A2C0A', bg = '#C8834A' })
  vim.api.nvim_set_hl(0, 'Visual', { bg = '#EDE0CC' })
  vim.api.nvim_set_hl(0, 'Comment', { fg = '#7B5033', italic = true })
  vim.api.nvim_set_hl(0, 'String', { fg = '#C8834A' })
  vim.api.nvim_set_hl(0, 'Character', { fg = '#C8834A' })
  vim.api.nvim_set_hl(0, 'Number', { fg = '#0077B6' })
  vim.api.nvim_set_hl(0, 'Boolean', { fg = '#6B4FA0' })
  vim.api.nvim_set_hl(0, 'Float', { fg = '#0077B6' })
  vim.api.nvim_set_hl(0, 'Function', { fg = '#4CAF50' })
  vim.api.nvim_set_hl(0, 'Keyword', { fg = '#D32F2F' })
  vim.api.nvim_set_hl(0, 'Statement', { fg = '#D32F2F' })
  vim.api.nvim_set_hl(0, 'Conditional', { fg = '#D32F2F' })
  vim.api.nvim_set_hl(0, 'Repeat', { fg = '#D32F2F' })
  vim.api.nvim_set_hl(0, 'Label', { fg = '#6B4FA0' })
  vim.api.nvim_set_hl(0, 'Operator', { fg = '#7B5033' })
  vim.api.nvim_set_hl(0, 'Title', { fg = '#C8834A', bold = true })
  vim.api.nvim_set_hl(0, 'Identifier', { fg = '#4A2C0A' })
  vim.api.nvim_set_hl(0, 'Type', { fg = '#0077B6' })
  vim.api.nvim_set_hl(0, 'Structure', { fg = '#6B4FA0' })
  vim.api.nvim_set_hl(0, 'Special', { fg = '#6B4FA0' })
  vim.api.nvim_set_hl(0, 'PreProc', { fg = '#4CAF50' })
  vim.api.nvim_set_hl(0, 'Define', { fg = '#4CAF50' })
  vim.api.nvim_set_hl(0, 'Macro', { fg = '#4CAF50' })
  vim.api.nvim_set_hl(0, 'Include', { fg = '#4CAF50' })
  vim.api.nvim_set_hl(0, 'Error', { fg = '#C62828', bg = '#FFF8F0' })
  vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#C62828' })
  vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#E65100' })
  vim.api.nvim_set_hl(0, 'Underlined', { fg = '#4A2C0A', underline = true })
  vim.api.nvim_set_hl(0, 'Ignore', { fg = '#F5EBD8' })
  vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#2E7D32', bg = '#F5EBD8' })
  vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#E65100', bg = '#F5EBD8' })
  vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#C62828', bg = '#F5EBD8' })
  vim.api.nvim_set_hl(0, 'DiffText', { fg = '#FFF8F0', bg = '#C8834A' })
  vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#4A2C0A', bg = '#F5EBD8', reverse = false })
  vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#7B5033', bg = '#EDE0CC', reverse = false })
  vim.api.nvim_set_hl(0, 'TabLine', { fg = '#7B5033', bg = '#EDE0CC' })
  vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#4A2C0A', bg = '#FFF8F0', bold = true })
  vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#F5EBD8' })
  vim.api.nvim_set_hl(0, 'Cursor', { fg = '#FFF8F0', bg = '#C8834A' })
  vim.api.nvim_set_hl(0, 'CursorIM', { link = 'Cursor' })
  vim.api.nvim_set_hl(0, 'TermCursor', { link = 'Cursor' })
end
return M
